apiVersion: v1
kind: Service
metadata:
  name: bionic-vm-ssh
  namespace: vm-objects
spec:
  ports:
  - name: bionic-vm-ssh
    nodePort: 30120
    protocol: TCP
    port: 22
    targetPort: 22
  selector:
    kubevirt.io/vm: bionic-image-vm
  type: NodePort
